famous_people = [
{'rank':1 ,	'name':'Instagram'              ,'followers':579,	'country':'United States'                          ,'activity': 'Social media platform'},
{'rank':2 ,	'name':'Cristiano Ronaldo'		,'followers':519, 	'country':'Portugal'                                ,'activity': 'Footballer'},
{'rank':3 ,	'name':'Lionel Messi'			,'followers':400,	'country':'Argentina'                               ,'activity': 'Footballer'},
{'rank':4 ,	'name':'Kylie Jenner'			,'followers':375,	'country':'United States'							,'activity': 'Television personality, model and businesswoman'},
{'rank':5 ,	'name':'Selena Gomez'			,'followers':364,	'country':'United States'							,'activity': 'Musician, actress, and businesswoman'},
{'rank':6 ,	'name':'Dwayne Johnson'			,'followers':354,	'country':'United States'							,'activity': 'Actor and professional wrestler'},
{'rank':7 ,	'name':'Ariana Grande'			,'followers':345,	'country':'United States'							,'activity': 'Musician, actress and businesswoman'},
{'rank':8 ,	'name':'Kim Kardashian'			,'followers':336,	'country':'United States'							,'activity': 'Television personality, model and businesswoman'},
{'rank':9 ,	'name':'Beyoncé'				,'followers':287,	'country':'United States'							,'activity': 'Musician, actress and businesswoman'},
{'rank':10,	'name':'Khloé Kardashian'		,'followers':283,	'country':'United States'							,'activity': 'Television personality and model'},
{'rank':11,	'name':'Justin Bieber'			,'followers':270,	'country':'Canada'									,'activity': 'Musician'},
{'rank':12,	'name':'Kendall Jenner'			,'followers':267,	'country':'United States'							,'activity': 'Model and television personality'},
{'rank':13,	'name':'Nike'					,'followers':257,	'country':'United States'							,'activity': 'Sportswear multinational'},
{'rank':14,	'name':'National Geographic'	,'followers':251,	'country':'United States'							,'activity': 'Magazine'} ,
{'rank':15,	'name':'Taylor Swift'			,'followers':236,	'country':'United States'							,'activity': 'Musician and actress'},
{'rank':16,	'name':'Jennifer Lopez'			,'followers':229,	'country':'United States'							,'activity': 'Musician and actress'},
{'rank':17,	'name':'Virat Kohli'			,'followers':227,	'country':'India'									,'activity': 'Cricketer'},
{'rank':18,	'name':'Nicki Minaj'			,'followers':206,	'country':'Trinidad and Tobago/United States'		,'activity': 'Musician'},
{'rank':19,	'name':'Kourtney Kardashian'	,'followers':206,	'country':'United States'							,'activity':   'Television personality and model'},
{'rank':20,	'name':'Neymar'					,'followers':196,	'country':'Brazil'									,'activity': 		     		    'Footballer'},
{'rank':21,	'name':'Miley Cyrus'			,'followers':190,	'country':'United States'							,'activity': 			  'Musician and actress'},
{'rank':22,	'name':'Katy Perry '			,'followers':183,	'country':'United States'							,'activity': 			    		  'Musician'},
{'rank':23,	'name':'Zendaya'				,'followers':161,	'country':'United States'							,'activity': 			    'Actress and singer'},
{'rank':24,	'name':'Kevin Hart'				,'followers':160,	'country':'United States'							,'activity': 			    'Comedian and actor'},
{'rank':25,	'name':'Cardi B'				,'followers':145,	'country':'United States'							,'activity': 		'Musician and businesswoman'},
{'rank':29,	'name':'Real Madrid CF'			,'followers':129,	'country':'United States'							,'activity': 				   	 'Football club'},
{'rank':30,	'name':'Ellen DeGeneres'		,'followers':129,	'country':'United States'							,'activity':'Comedian and television personality'},
{'rank':31,	'name':'Drake'					,'followers':127,	'country':'Barbados'             					,'activity': 						  'Musician'},
{'rank':32,	'name':'Chris Brown'			,'followers':127,	'country':'United States'							,'activity': 				          'Musician'},
{'rank':33,	'name':'FC Barcelona'			,'followers':115,	'country':'Spain'									,'activity': 				     'Football club'},
{'rank':34,	'name':'Billie Eilish'			,'followers':107,	'country':'United States'							,'activity': 				          'Musician'},
{'rank':35,	'name':'UEFA Champions League'	,'followers':101,	'country':'Europe'									,'activity': 		 'Club football competition'},
{'rank':36,	'name':'Gal Gadot'				,'followers':92.2,	'country':'Israel'									,'activity': 		                   'Actress'},
{'rank':37,	'name':'Dua Lipa'				,'followers':87.5,	'country':'United Kingdom/Albania'					,'activity': 				          'Musicianm/Albania'},
{'rank':38,	'name':'NASA'					,'followers':85.7,	'country':'United States'							,'activity': 				      'Space agency'},
{'rank':39,	'name':'Lisa'					,'followers':85.4,	'country':'Thailand'	    						,'activity': 				          'Musician'},
{'rank':40,	'name':'Vin Diesel'				,'followers':85,	'country':'United States'							,'activity': 				             'Actor'},
{'rank':41,	'name':'Kylian Mbappé'			,'followers':84.3,	'country':'France'							        ,'activity': 				        'Footballer'},
{'rank':42,	'name':'Priyanka Chopra '		,'followers':84,	'country':'India'									,'activity': 			  'Actress and musician'},
{'rank':43,	'name':'Khaby Lame'				,'followers':80.2,	'country':'Italy/Senegal'							,'activity': 		  'Social media personality'},
{'rank':44,	'name':'Snoop Dogg'				,'followers':78.3,	'country':'United States'							,'activity': 			              'Musician'},
{'rank':45,	'name':'Shakira'				,'followers':77.8,	'country':'Colombia'									,'activity': 				          'Musician'},
{'rank':46,	'name':'Shraddha Kapoor'		,'followers':76.7,	'country':'India'									,'activity': 				           'Actress'},
{'rank':47,	'name':'David Beckham'			,'followers':76.4,	'country':'United Kingdom'							,'activity': 				        'Footballer'},
{'rank':48,	'name':'Gigi Hadid'				,'followers':76.4,	'country':'United States'							,'activity': 				             'Model'},
{'rank':49,	'name':"Victoria's Secret"		,'followers':73.8,	'country':'United States'							,'activity': 				  'Lingerie company'},
{'rank':50,	'name':'Alia Bhatt'				,'followers':73.5,	'country':'United Kingdom/India'						,'activity': 			  'Actress and musician'},
]